language: node_js

node_js:
  - '0.10'

branches:
  except:
    - gh-pages

before_install:
  - gem update --system
  - gem install compass

env:
  global:
    - REPO="git@github.com:appleboy/backbone-template-engine.git"

after_success: build/after_success.sh
