language: node_js

node_js:
  - '0.10'

branches:
  except:
    - gh-pages

before_install:
  - npm install -g bower
  - gem update --system
  - gem install compass

env:
  global:
    - REPO="git@github.com:appleboy/backbone-template-engine"
    - secure: "idH+siInovXZvIP2HDGNc/FTu6/Th9zb1MCqYh2ORQhgOPo3L4giz3cGuTT37VsRl1kVLZHXNliHw++gsYcZvMJNkdSTDa/h4bGGi1FbxA734wKyl2uns82OglnYqzqKKc3CBzEEohEJdPlJXfHmBAV4xiH200BIE6d2XQlCOhY="

after_success: build/after_success.sh
